### ISSUE TITLE
Check code validity even when no system was provided (where appropriate)

### ISSUE THREAD

**Issue by nir-r** [Outburn-IL/fume-community#131]
In the attached example, if the ValueSet can by fully $expand(ed) AND no new values can be introduced (binding strength is "required") => validate code against it even when no system was provided AND raise a warning for lack of system.

![image](https://github.com/user-attachments/assets/853ea806-5753-466c-aef9-6c83825abe95)

**Comment by mechanik-daniel** [comment]
Duplicate of #130
