### ISSUE TITLE
422 Unprocessable Entity : Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by jurigaranin** [Outburn-IL/fume-community#2]
Hello

I installed and started the server.

**The Get method at http://localhost:42420/ JSON response :**

```
{
   "public_sandbox": "https://try.fume.health",
   "api_instructions": "POST a JSON object to this endpoint, containing an input json value and a FUME expression.",
   "example_body": {
     "input": {
       "values": [
         "value1",
         "value2"
       ]
     },
     "fume": "values[1]",
     "contentType": "application/json"
   },
   "should_return": "value2"
}
```

**I try to POST a JSON object to this endpoint, but the response is always the same.**

422 Unprocessable Entity

```
{
   "__isFumeError": true,
   "message": "Cannot read properties of undefined (reading 'replace')",
   "code": "",
   "name": "TypeError",
   "token": "splitLineFunc",
   "cause": "",
   "position": 37
}
```

**Body I sent:**

```
{
   "input": {
     "values": [
       "value1",
       "value2"
     ]
   },
   "fume": "values[1]",
   "contentType": "application/json"
}

```
What am I doing wrong? Is there an error somewhere in the post request body?

@mechanik-daniel @kaplanlior

**Comment by mechanik-daniel** [comment]
Hi,
This is an error that you get if you send the body as text. Please make sure you pass a Content-Type http header with "application/json" and not "text/plain".

**Comment by mechanik-daniel** [comment]
Some screenshots that may help:

When this is set:
![image](https://github.com/Outburn-IL/fume-community/assets/91424710/20107ff7-2094-4d3e-acd3-2d95ea178e08)

This is the default header that is sent, and the error that you encountered is what you get:
![image](https://github.com/Outburn-IL/fume-community/assets/91424710/824961ae-9bee-4c72-b033-5382151b5ce8)

But when you set this:
![image](https://github.com/Outburn-IL/fume-community/assets/91424710/89333517-071e-4560-81b4-8c04712c891a)


The Content-Type is set to application/json and you get a valid response:
![image](https://github.com/Outburn-IL/fume-community/assets/91424710/e61058e8-113e-4ca9-a82d-7c5fd3f408bc)
